BATCH_SIZE: 6
WORKERS: 8

OPTIMIZER: AdamW
STEPSIZE: 1
BASE_LR: 0.0002 # 0.00002
#MOMENTUM: 0.9
WEIGHT_DECAY: 0.001 # 0.0001
OPTIM_BETAS: (0.9, 0.999)

IGNORE_LABEL: 255

SCHEDULER: PolynomialLR  # PolynomialLR  # ReduceLROnPlateau  # ExponentialLR
WARMUP_LR: 0.0
MIN_LR: 0.0000001 # 0.000001
MAX_EPOCH: 1 #500
MAX_ITER: 150
POWER: 0.9

CE_BCE: 0.5
DICE: 0.3
LOVASZ: 0.2


THRESHOLD: 0.0001
PATIENCE: 10
OPTIMIZER_FORM: single



