BATCH_SIZE: 32
WORKERS: 16

OPTIMIZER: AdamW
BASE_LR: 0.0001  # 0.00002
#MOMENTUM: 0.9
WEIGHT_DECAY: 0.001 # 0.0001
OPTIM_BETAS: (0.9, 0.999)

IGNORE_LABEL: 255

SCHEDULER: PolynomialLR  # PolynomialLR  # ReduceLROnPlateau  # ExponentialLR
WARMUP_LR: 0.0
MIN_LR: 0.0000001 # 0.000001
MAX_EPOCH: 500
POWER: 0.3

OPTIMIZER_FORM: single



