#Training hyperparmeters

INTERVALS: 60 # 60/2
EPOCH: 2 #180
PRECISION: 16-mixed
DEVICES: 1 #[2,3]
#lr Scheduler
WEIGHT_DECAY: 0.05
FACTOR: 0.1
#POLYNOMIAL
THRESHOLD: 0.001
PATIENCE: 10
LR: 0.0001
STEP: 1
POWER: 0.3
MIN_LR: 0.000001
WORKERS: 0
BATCH_SIZE: 1
ID2LABEL:
   0: "SKIN"
   1: "Non_SKIN"
#   0: "BACKGROUND"
#   1: "SKIN"
#   2: "NOSE"
#   3: "RIGHT_EYE"
#   4: "LEFT_EYE"
#   5: "RIGHT_BROW"
#   6: "LEFT_BROW"
#   7: "RIGHT_EAR"
#   8: "LEFT_EAR"
#   9: "MOUTH_INTERIOR"
#   10: "TOP_LIP"
#   11: "BOTTOM_LIP"
#   12: "NECK"
#   13: "HAIR"
#   14: "BEARD"
#   15: "CLOTHING"
#   16: "GLASSES"
#   17: "HEADWEAR"

