#Training hyperparmeters

EPOCH: 1 #180
PRECISION: 16-mixed
DEVICES: 1 #[2,3]
#lr Scheduler
# POLYNOMIAL_POWER: 0.9
PATIENCE: 30
LR: 0.001
FACTOR: 0.1
# MIN_LR: 8
WORKERS: 8
BATCH_SIZE: 2
ID2LABEL:
    0: 'Non_Skin'
    1: 'Skin'

