NAME: SegNext

BACKBONE:
  depths:
    - 3
    - 5
    - 27
    - 3
  drop_path_rate: 0.3
  embed_dims:
    - 64
    - 128
    - 320
    - 512
  mlp_ratios:
    - 8
    - 8
    - 4
    - 4
  norm_cfg:
    requires_grad: true
    type: BN
  type:
    MSCAN

DECODER_HEAD:

  channels: 1024
  ham_channels: 1024
  ham_kwargs:
    MD_R: 16
    MD_S: 1
    eval_steps: 7
    inv_t: 100
    rand_init: true
    train_steps: 6
  in_channels:
    - 128
    - 320
    - 512
  in_index:
    - 1
    - 2
    - 3

  norm_cfg:
    num_groups: 32
    requires_grad: true
    type: GN
  num_classes: 1
  type:
    LightHamHead

init_cfg:
  checkpoint:
        https://download.openmmlab.com/mmsegmentation/v0.5/segnext/segnext_mscan-l_1x16_512x512_adamw_160k_ade20k/segnext_mscan-l_1x16_512x512_adamw_160k_ade20k_20230209_172055-19b14b63.pth
  type: pretrained

