NAME: SegNext

BACKBONE:

  depths:
    - 3
    - 5
    - 27
    - 3
  drop_path_rate: 0.3
  embed_dims:
    - 64
    - 128
    - 320
    - 512
#  init_cfg:
#    checkpoint: 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segnext/mscan_l_20230227-cef260d4.pth'
#    type: 'Pretrained'
  mlp_ratios:
    - 8
    - 8
    - 4
    - 4
  norm_cfg:
    requires_grad: true
    type: 'BN'


DECODER_HEAD:

  channels: 1024
  ham_channels: 1024
  ham_kwargs:
    MD_R: 16
    MD_S: 1
    eval_steps: 7
    inv_t: 100
    rand_init: true
    train_steps: 6
  in_channels:
    - 128
    - 320
    - 512
  in_index:
    - 1
    - 2
    - 3

  norm_cfg:
    num_groups: 32
    requires_grad: true
    type: 'GN'
  num_classes: 1




