NAME: SegNext

BACKBONE:
  act_cfg:
    type: 'GELU'
  attention_kernel_paddings:
    - 2
    - [ 0, 3 ]
    - [ 0, 5 ]
    - [ 0, 10 ]
  attention_kernel_sizes:
    - 5
    - [ 1, 7 ]
    - [ 1, 11 ]
    - [ 1, 21 ]
  depths:
    - 3
    - 5
    - 27
    - 3
  drop_path_rate: 0.3
  drop_rate: 0.0
  embed_dims:
    - 64
    - 128
    - 320
    - 512
  init_cfg:
    checkpoint: 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segnext/mscan_l_20230227-cef260d4.pth'
    type: 'Pretrained'
  mlp_ratios:
    - 8
    - 8
    - 4
    - 4
  norm_cfg:
    requires_grad: true
    type: 'BN'
  type: 'MSCAN'

DECODER_HEAD:
  align_corners: false
  channels: 1024
  dropout_ratio: 0.1
  ham_channels: 1024
  ham_kwargs:
    MD_R: 16
    MD_S: 1
    eval_steps: 7
    inv_t: 100
    rand_init: true
    train_steps: 6
  in_channels:
    - 128
    - 320
    - 512
  in_index:
    - 1
    - 2
    - 3
#    loss_decode:
#      loss_weight: 1.0
#      type: 'CrossEntropyLoss'
#      use_sigmoid: false
  norm_cfg:
    num_groups: 32
    requires_grad: true
    type: 'GN'
  num_classes: 1
  type: 'LightHamHead'



