NAME: Swin_Unet

SWIN:
  PATCH_SIZE: 4
  EMBED_DIM: 96
  DEPTHS: [ 2, 2, 2, 2 ]
  NUM_HEADS: [ 3, 6, 12, 24 ]
  WINDOW_SIZE: 7
  MLP_RATIO: 4.
  QKV_BIAS: true
  QK_SCALE: null
  APE: false
  PATCH_NORM: true

USE_CHECKPOINT: false
DROP_RATE: 0.
DROP_PATH_RATE: 0.2
